[package]
name = "arcagent"
version = "0.1.0"
edition = "2024"

[dependencies]
tempfile = "3.20.0"
chrono = "0.4"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "migrate"] }
tokio = { version = "1.45.1", features = ["full"] }
async-openai = "0.28.3"
